name: cf-env
channels:
  - conda-forge
  - pytorch
dependencies:
  - tqdm
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - cudatoolkit=11.3
  - pip:
    - mpl-chord-diagram
    - chord
    - tslearn
    - wildboar

